### ISSUE TITLE
Unable to update charge_interval_frequency

### ISSUE THREAD

**Issue by tispratik** [ScreenStaring/recharge-api#1]
Am getting the following error when trying to update the charge interval frequency on a subscription:

```
>> subscription.charge_interval_frequency = 1
=> 1
>> s.save
Recharge::RequestError: 400 - BAD REQUEST
	from /Users/me/.rvm/gems/ruby-2.2.3/gems/recharge-api-0.0.1/lib/recharge/http_request.rb:75:in `block in request'
	from /Users/me/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/me/.rvm/gems/ruby-2.2.3/gems/recharge-api-0.0.1/lib/recharge/http_request.rb:67:in `request'
	from /Users/me/.rvm/gems/ruby-2.2.3/gems/recharge-api-0.0.1/lib/recharge/http_request.rb:28:in `PUT'
	from /Users/me/.rvm/gems/ruby-2.2.3/gems/recharge-api-0.0.1/lib/recharge/http_request.rb:219:in `update'
	from /Users/me/.rvm/gems/ruby-2.2.3/gems/recharge-api-0.0.1/lib/recharge/classes.rb:216:in `save'
	from (irb):101
	from /Users/me/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
```

**Comment by sshaw** [comment]
`Recharge::RequestError` has [an `#errors` method](http://www.rubydoc.info/gems/recharge-api/Recharge/RequestError). What does it return? 

It's likely that your subscription is in a state that prevents setting `charge_interval_frequency`.

**Comment by sshaw** [comment]
Closing as it does not look like a bug and no additional information was provided. Feel free to reopen if necessary.
